APP-Android2/FinalProject-modigm

app/build.gradle.kts, build.gradle.kts
=> chore #6: 파이어베이스와 프로젝트를 연결

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/adapter/JoinViewPagerAdapter.kt, app/src/main/res/layout/fragment_join.xml, app/src/main/res/layout/fragment_join_step1.xml, app/src/main/res/layout/fragment_join_step2.xml, app/src/main/res/layout/fragment_join_step3.xml
> #24 
> 회원 가입 부분 화면 작업 및 viewpager로 화면이동하는 것까지만 구현했습니다
| 이메일, 비밀번호 | 이름, 전화번호 | 관심분야 |
| - | - | - |
| <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/7598f5b0-cc00-4284-a8e3-57845aa776dd" width=250> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/d8c1e1a2-6bf3-4ca0-97bf-45db18add075" width=250> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/410f7d36-d101-4d0a-9d78-a85d688da58e" width=250> |
[Screen_recording_20240522_171257.webm](https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/afa32eaf-09e2-4832-87bc-58f2615f9a60)
>
=> [#24] feature 회원 가입 UI 작업

app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt, app/src/main/res/drawable/icon_add_24px.xml, app/src/main/res/drawable/icon_arrow_up_24px.xml, app/src/main/res/drawable/icon_back_24px.xml, app/src/main/res/drawable/icon_more_vert_24px.xml, app/src/main/res/drawable/icon_search_24px.xml, app/src/main/res/drawable/style_button_send_gray_chatroom.xml, app/src/main/res/drawable/style_edittext_chatroom.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_chat.xml, app/src/main/res/layout/fragment_chat_group.xml, app/src/main/res/layout/fragment_chat_oneto_one.xml, app/src/main/res/layout/fragment_chat_room.xml, app/src/main/res/layout/row_chatroom_filed.xml, app/src/main/res/menu/menu_chat_toolbar.xml, app/src/main/res/menu/menu_chatroom_toolbar.xml, app/src/main/res/menu/popup_menu_chatroom_more_vert.xml
> ex) #23 - 채팅 UI 관련 추가
> 채팅(상단 탭 - 이동 가능, 리사이클러 뷰 세팅, 툴바 검색은 아이콘만), 채팅 방(하단 채팅 탭 및 채팅 시 버튼 색상 변경) 설정완료
> 텍스트 입력 칸과 텍스트 버튼의 Radius(둥글게하는거) 설정이랑 채팅 방 리사이클러 뷰는 아직 구현 못했습니다.
> 이게 내가 채팅칠때와 상대가 채팅칠때 왼쪽 오른쪽에서 다르게 나와야되는데 구현해야할지 help me... 리사이클러 뷰는 맞을까요?
> 텍스트 입력 칸을 어떻게 figma 처럼 둥그렇게 만들까요?
=> [#23] feature - 채팅 UI 관련 추가

App bar/1. Top/A. Regular/Arrow back.svg, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt, app/src/main/res/drawable/arrow_back_24px.xml, app/src/main/res/drawable/tab_background.xml, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/fragment_write_field.xml, app/src/main/res/layout/fragment_write_intro.xml, app/src/main/res/layout/fragment_write_period.xml, app/src/main/res/layout/fragment_write_proceed.xml, app/src/main/res/layout/fragment_write_skill.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
> #29 
> Toolbar 생성
> Progress Bar 생성
> ViewPager 사용
> Indicator 크기 조정
> WriteFragment 화면
> 위의 사진인 `TabLayout의 배경 색상`과 `Progress Bar의 미진행 부분의 색상`을 변경하고 싶은데 구글링해서 적용은 했는데 xml 미리보기 상에서는 변경되지 않은 것 같아서.. 제대로 된 것이 맞는지 확인 부탁드립니다 
> 빠른 코드보기..
=> [#29] feature 스터디 글 작성 화면 UI

app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/res/drawable/tab_background.xml, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/fragment_write_field.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
> #30 
> 화면 작업(TextView, Button)
> 버튼 디자인 설정(Outlined) -> 카드(Card View)로 구현
> 카드 뷰 선택시 효과 및 리스너 설정
> '다음' 버튼 클릭 시 탭 전환 
> 내일 오전에 PR 확인하시고 문제 없으면 머지하겠습니다
=> [#30] feature 스터디 글 작성 화면 탭분야

app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt, app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt, app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt
=> [Feature] #43 프래그먼트 전환

app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt, app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt, app/src/main/res/drawable/style_message_received.xml, app/src/main/res/drawable/style_message_sent.xml, app/src/main/res/layout/fragment_chat_oneto_one.xml, app/src/main/res/layout/fragment_chat_room.xml, app/src/main/res/layout/item_message_received.xml, app/src/main/res/layout/item_message_sent.xml
> #37
> 채팅방에서의 대화 내용 UI 추가 및 텍스트 입력 후 전송 버튼 기능
아직 상대편 이름에 프로필 사진 넣는 칸을 구현하지 못했습니다.
UI 수정해야 할 곳이 있거나 고쳐야 될 부분이 있다면 말씀 부탁드립니다!
따로 말씀 없으시다면 14:00시에 Merge 해두겠습니다!
=> [Feature] #37 채팅방 대화 내용 (UI, 기능)

app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt, app/src/main/res/layout/fragment_other_login.xml
=> [#46]  Fix - Fragment 이동관련 및 xml 오류 해결

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt, app/src/main/res/layout/fragment_join.xml, app/src/main/res/layout/fragment_join_step2.xml, app/src/main/res/layout/fragment_join_step3.xml
> #36 
> 회원가입 시 입력값 유효성 검사
> 프로그래스바 연동
> 다음 버튼 위치 수정
> 뒤로가기 아이콘 수정
> 중복 가입 알림 화면은 깜빡해서 새로 브랜치 파고 추가 작업하겠습니다
| 이메일, 비밀번호 | 이름, 전화번호 | 관심분야 |
|--|--|--|
| <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/c0474939-8d1d-4178-a651-454ab20283f3" width=250 /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/533c2fab-cd0a-4357-acd4-0756199d6c81" width=250 /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/96fa4b4e-c1a7-49d5-af45-2df3c7f3ab2a" width=250 /> |
> 유효성 검사 관련해서 빠진 부분이 있다거나 더 괜찮은 방향이 있다면 반영해보겠습니다
> 비밀번호는 영문, 숫자, 특수문자 포함 8~20 문자로 임의 셋팅했습니다 이 기준에 대한 아이디어 있으시면 말씀 부탁드리겠습니다.
=> [#36] feature 회원 가입 입력 관련 기능 구현

app/src/main/res/layout/fragment_edit_profile.xml
#62 
fragment_edit_profile.xml의 잘못된 어트리뷰트 helpertextcolor 삭제 및 올바른 위치에 추가
=> fix #62: fragment_edit_profile.xml 수정

app/build.gradle.kts, app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt, app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatMessagesDao.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
> #64
채팅 방 관련해서 Model, ViewModel, 간단하게 채팅 방 생성, 가져오기를 Dao 에 추가 하였습니다
채팅 방 임시 데이터 => Firebase 데이터로 변경 되게 하였습니다.
UI 변동이 없으므로 동일
UI 변경은 없으며 채팅 방 Model, ViewModel 생성 Dao 정도만 있어서 확인 해보시고 이상 없다면
오늘까지 머지 하도록 하겠습니다.
=> [#64] feature 채팅 방 목록 관련 ViewModel, Model 추가 및 Firebase 연동

app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/res/layout/fragment_write_proceed.xml
> #66
> 모집 글 작성 탭(진행방식)
> 화면 UI 구성
=> [#66] feature 모집 글 작성 탭진행방식

app/build.gradle.kts
> #76 
> 파이어베이스 인증 기능 사용을 위해 모듈(앱 수준) Gradle 파일에 Firebase Authentication 종속 항목 추가
>
=> [#76] feature  모듈(앱 수준) Gradle 파일에 Firebase Authentication 종속 항목 추가

app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt, app/src/main/res/layout/fragment_write_skill.xml
>#87
> 탭(기술) 관련 화면 작업 
> '필요한 기술스택' 클릭 시 올라오는 바텀 시트는 아직 회의가 덜 이루어진 부분이 있는 것 같아 미구현 상태로 냅두었습니다
=> [#87] feature 모집 글 작성 탭기술

app/google-services.json
#90 
firebase 프로젝트를 생성하고 google-services.json 파일을 그에 맞게 변경함
=> fix #90: google-services.json 변경

app/src/main/java/kr/co/lion/modigm/ui/write/CustomDialogWriteIntroExample.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/more/BottomSheetWriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/more/CustomDialogWriteIntroExample.kt, app/src/main/java/kr/co/lion/modigm/ui/write/more/IndentLeadingMarginSpan.kt, app/src/main/res/drawable/icon_photo_plus_24px.xml, app/src/main/res/drawable/style_custom_dialog_write_intro_example.xml, app/src/main/res/layout/custom_dialog_write_intro_example.xml, app/src/main/res/layout/fragment_bottom_sheet_write_proceed.xml, app/src/main/res/layout/fragment_write_intro.xml
> #89
> 화면 작업
> 커스텀 다이얼로그 화면 작업
=> [#89] feature 모집 글 작성 탭 - 소개

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #106 
> 이메일 계정 가입 과정에서 인증 에러가 나는 부분들을 수정했습니다.
>
> 주교수님이 추천하신대로 직접 프래그먼트를 참조하지 않고 activityViewModels로 뷰모델만 공유하여 사용할 수 있도록 변경해보았습니다.
>
> 프래그먼트끼리 공유가 필요한 뷰모델을 activityViewModels로 초기화해서 사용하면 서로 같은 뷰모델을 공유하는 것으로 이해했는데 코드 보시고 사용법이 잘못된 부분이 있다면 말씀 부탁드리겠습니다.
=> [#106] feature 파이어베이스 전화번호 인증 에러 처리

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt, app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/model/StudyData.kt, app/src/main/java/kr/co/lion/modigm/model/UserData.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/adapter/HostStudyViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
=> #115 feature: studydata 필드 이름 수정

app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt, app/src/main/res/layout/fragment_chat.xml
> #109 
채팅 방 툴바 → 채팅 방 목록 검색기능 ( O )
>
=> [#109] feature - 채팅 방 목록 검색기능

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt, app/src/main/res/layout/fragment_detail.xml, app/src/main/res/layout/fragment_detail_edit.xml
>#132
> 주소 선택 바텀시트에 상세주소 출력
| 주소 선택 후 화면 |
|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/60d2fcef-9ef2-46c8-bfe0-a682bf513bde" /> | 
>
=> [Feature #132] 주소 선택 상세주소 추가

app/src/main/AndroidManifest.xml, app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt, app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt, app/src/main/java/kr/co/lion/modigm/util/PreferenceUtil.kt, app/src/main/res/layout/fragment_find_email.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_other_login.xml
> #144 
이메일 로그인 구현
로그인 유효성 검사 적용
자동로그인 구현(소셜 로그인 포함)
|로그인 화면 1|로그인 화면 2|
|:--------------:|:--------------:|
|<img width="225" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/fe8579fe-28e4-4432-8e14-04e3ab91bf8f">|<img width="225" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/02605364-5efe-4fb4-9582-074b6ec9b1f3">|
|유효성검사 이메일|유효성검사 패스워드|이메일을 틀렸을 경우|
|:-------------------:|:-----------------------:|:-------------------:|
|<img width="308" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/c7b6519b-946e-43af-a495-40e6015d14fa">|<img width="308" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/caef39c4-e95b-407f-99d1-be69b3231dcf">|<img width="308" …
=> [#144] [Feature] 이메일 로그인 및 자동로그인

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #162 
> 이메일 계정 회원가입 후 로그인 페이지로 돌아오기
> popBackStack 잘못된 부분을 다시 수정했습니다
[emailjoin.webm](https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/e2167778-412a-450a-9103-3d938c5b78c5)
>
> 현재 devleop 브랜치에 회원가입 기능 구현이 되어있어 직접 SNS 계정이나 이메일 계정 만들어보시고 에러가 나는 부분이 있다면 알려주십쇼!
=> [#162] feature 이메일 계정 회원가입 후 로그인 페이지로 되돌아오기

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
#178 
DetailFragment에서 채팅 방으로 입장하는 코드 추가
>
=> [#178] feat - DetailFragment - 채팅 방으로 입장하는 코드 추가

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #180 
> 회원 가입 시 파이어스토어에 저장되는 회원 정보 중 이메일이 누락되는 부분이 있어서 수정했습니다.
>
=> [Fix] #180 회원 가입 시 이메일 데이터가 누락되는 부분 수정

app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/vm/ChangePhoneViewModel.kt, app/src/main/res/layout/fragment_change_phone.xml
> #183 
> 핸드폰 번호 변경 기능
> 안드로이드 에뮬레이터에서 캡챠가 깨져보여서 실제 번호로는 테스트해보지는 못했습니다.
테스트 번호로 했을때는 잘 바뀌는 부분 확인했습니다.
> RemoteUserDataSource와 UserInfoRepository에 메서드 추가했습니다. 참고 부탁드리겠습니다.
=> [#183] feature 핸드폰 번호 변경 기능

app/src/main/java/kr/co/lion/modigm/db/like/RemoteLikeDataSource.kt, app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt, app/src/main/java/kr/co/lion/modigm/model/StudyData.kt, app/src/main/java/kr/co/lion/modigm/repository/LikeRepository.kt, app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/like/LikeFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/like/adapter/LikeAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/like/vm/LikeViewModel.kt
> #175
> 좋아요 기능 구현
> 이미지부분은 나중에 추가구현 하겠습니다!
>
=> [Feature #175] 좋아요 기능

app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/more/BottomSheetWriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt, app/src/main/res/layout/fragment_write_proceed.xml
> #154
> 기간 탭 - MVVM(진행기간) 적용
> 진행방식 탭 - MVVM(진행방식, 스터디 인원) 적용
> 기술 탭 - MVVM(신청방식, 필요한 기술 스택) 적용
> 소개 탭 - MVVM(커버사진, 글 제목, 글 내용) 적용
=> [#154] feature 스터디 글 작성 나머지 탭 mvvm 구조

app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt, app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt, app/src/main/res/layout/fragment_change_phone.xml
> #193 
> 전화번호 변경 화면 툴바 추가
> 인증번호 유효성 검사 추가
> 인증번호 입력창 inputType number로 변경
> popBackStack 수정
>
=> [#193] feature 전화 번호 변경 화면 수정

app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
> #190
> 완료 버튼 클릭 시 DB에 데이터 전송이 끊기는 문제 해결했습니다
=> [#190] fix db 연동 오류 수정

app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
#194 
1:1 채팅 방 Title 데이터 처리 수정
로그인 처리 수정
채팅방 화면전환 처리
화면 UI 변화 없으며 데이터 처리하는 쪽만 수정했습니다.
=> [#194] feature - chatting data 데이터 처리 수정

app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt, app/src/main/res/layout/fragment_edit_profile.xml
#198 
추후에 적겠습니다
- 데이터베이스 변경까지는 되는데 UI 변경은 아직 안됩니다
=> #198 feature: 프로필 수정 시 데이터베이스에 저장

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
> #202
> 멤버목록에서 사용자 프로필 보기
> 글 수정에 업로드 데이터 추가(studyData에 추가된 부분들이 있어서 수정했습니다)
> 글씨 크기가 커보이는건 제 단말기 글씨 크기가 최대로 되어 있어서 그런거라 확인하시고 고쳐주시거나 아니면 제가 나중에 고쳐두겠습니다 ㅎㅎ
|참여중 멤버 | 프로필 보기 |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/cefd9c40-5ec0-478d-bd3d-1bc34c3c644e" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/26406e99-d465-4520-9090-6732ee7b2d82" width=250 />|
|신청자 멤버 | 프로필보기 |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/a72882a0-985f-400a-879b-b3a1ab0691a1" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/0f82fd76-0db4-4e95-9481-67abce82c444" width=250 />|
>
> ex) 메서드 XXX의 이름을 더 잘 …
=> [Feature] 각 유저 프로필로 이동 연결

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/CustomFindEmailDialog.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindPwAuthFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindPwFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/ResetPwFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt, app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt, app/src/main/res/layout/custom_dialog_find_email.xml, app/src/main/res/layout/fragment_find_email_auth.xml, app/src/main/res/layout/fragment_find_pw.xml, app/src/main/res/layout/fragment_find_pw_auth.xml, app/src/main/res/layout/fragment_reset_pw.xml
> #192 
이메일 찾기 , 비밀번호 찾기 뷰작업만 완료한 상태입니다. 민식님께서 작업해주시기로 하셔서 넘겨드리기 위해 PR합니다!
화면전환은 uid 넘기는 부분 몇부분 보완했는데, 백스택이 아직 정리되지 않았을 수 있습니다. 이부분 다음 작업에서 같이 다루겠습니다!
=> [#192] [Feature] 화면 전환 및 이메일 비밀번호 찾기 구현

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
=> [Feature] fab버튼 클릭 추가

app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomMemberAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
#210
글 작성 시 채팅 방 생성 null 값 가져오는 오류
멤버 프로필 클릭 시 프로필 페이지로 이동
>
=> [#210] feature - 글 작성 시 채팅 방 생성 null 값 가져오는 오류

app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/fragment_write_intro.xml
> #223
> DB Uid 연동
> WriteFragment xml 파일 수정
> WriteIntroFragment xml 파일 수정
> DB Uid 데이터 연동 확인
> WriteFragment xml 파일 수정(이제야 발견한.. 버튼 상단 마진 수정)
> WriteIntroFragment xml 파일 수정( textField 입력받은 내용 : 한 줄 -> 여러 줄 변경)
> @diffngood setChatRoomData Uid 관련해서 일부 수정했습니다!
=> [#223] feature 글 작성 db uid 첨부 & WriteFragment, WriteIntroFragment xml 파일 수정

app/src/main/java/kr/co/lion/modigm/db/chat/ChatRoomDataSource.kt, app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt, app/src/main/java/kr/co/lion/modigm/repository/ChatRoomRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatSearchResultsAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatRoomViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
#222
(상세 페이지, 프로필 페이지)에서 1:1 채팅방 이동 가능(O)
- 만약 해당 1:1 채팅 방이 없다면 생성 있다면 기존에 있는 채팅방으로 입장
>
=> [#222] feat - 채팅 방 1:1 채팅 방 생성 및 이동

app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/login/CustomFindEmailDialog.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailAuthFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindEmailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailAuthViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindEmailViewModel.kt, app/src/main/res/layout/fragment_find_email.xml, app/src/main/res/layout/fragment_find_email_auth.xml
> #216 
> 이메일 찾기 기능 구현했습니다.
> 전화번호 인증이 완료되면 다이얼로그로 이메일을 표시해줍니다.
> 다이얼로그를 끄면 로그인 화면으로 되돌아갑니다.
>
> 다이얼로그는 성원님이 만들어주신 양식 그대로 활용했습니다
=> [#216] feature 이메일 찾기 기능

app/src/main/java/kr/co/lion/modigm/ui/login/FindPwAuthFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/FindPwFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/ResetPwFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPwAuthViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/FindPwViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/ResetPwViewModel.kt, app/src/main/res/layout/fragment_find_pw.xml, app/src/main/res/layout/fragment_find_pw_auth.xml, app/src/main/res/layout/fragment_reset_pw.xml
> #232 
> 비밀번호 재설정 기능
| 이메일, 전화번호 입력 | 인증번호 입력 | 새 비밀번호 설정 |
|--|--|--|
| <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/b2ead0eb-99ad-4b0a-b7ea-3c14d0eb2d6c" width="250" /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/f57160bc-9caa-4a47-9c03-73c15a9d6fa1" width="250" /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/942c586d-a20a-49c9-b72b-40838e64f9e4" width="250" /> |
|  |  | 완료 버튼 색깔은 파란색으로 바꾸었습니다 |
>
=> [#232] feature 비밀번호 재설정 기능

app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ChangePhoneFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt, app/src/main/res/layout/fragment_change_phone.xml, app/src/main/res/layout/fragment_profile_web.xml, app/src/main/res/menu/menu_profile_web.xml
#225 
1. 프로필 수정 시 사진을 storage에 업로드하고 화면 표시사항 변경
2. 프로필 수정 완료 후 스낵바 띄우기
3. 링크 눌렀을 때 앱이 튕기는 현상 해결
4. 전화번호 변경 시 바로 프로필 화면 업데이트
=> #225 feature: 프로필 관련 문제 해결

app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt, app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt, app/src/main/java/kr/co/lion/modigm/util/FilterSort.kt, app/src/main/res/layout/fragment_filter_sort.xml, app/src/main/res/layout/fragment_study.xml, app/src/main/res/layout/fragment_study_all.xml, app/src/main/res/layout/fragment_study_my.xml, app/src/main/res/layout/row_study_all.xml, app/src/main/res/layout/row_study_my.xml
> #230 
|전체 스터디 목록|필터 적용중|필터 적용 후|
|:------------------:|:------------:|:-------------:|
|<img width="293" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/9edb1b47-ebd5-44b4-80fd-9799524beb4d">|<img width="294" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/e492d8ad-cb09-4a56-8b58-734ee697247b">|<img width="294" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/30865512-1ed6-45d9-8035-244df798f3e2">|
FAB 버튼 사라지는 기능이랑 필터창의 적용 버튼 활성화 (색 전환) 나중에 하겠습니다....더는 못해....
=> [#230] [Feature] 필터 및 정렬 기능 구현

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt, app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDao.kt, app/src/main/java/kr/co/lion/modigm/db/write/RemoteWriteStudyDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep1ViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep3ViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #253 
> 회원가입 viewmodel에서 사용한 LiveData를 StateFlow로 변경했습니다.
>
> 데이터 바인딩을 사용하고 있는 상태에서 Flow는 asLiveData() 메서드로 LiveData처럼 데이터바인딩을 할 수 있게 해주는 작업이 필요한데 StateFlow는 이런 과정없이 LiveData처럼 데이터바인딩을 할 수 있어서 StateFlow로 변경했습니다.
SharedFlow는 여러 구독자에게 이벤트를 전파하는데 사용하면 된다고 하는데 회원가입에서 그러한 부분이 어디인지 아직 모르겠어서 SharedFlow가 아니라 StateFlow를 사용했습니다.
=> [#253] feature 회원가입 기능 flow 적용

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt, app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #255
> 회원가입 후 uid와 userdata 대신 userIdx를 sharedPreferences에 저장하는 것으로 수정했습니다.
>
=> [#255] feature 회원가입 후 userIdx를 sharedPreferences에 저장

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt, app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #262 
> runCatching을 사용해서 회원가입기능 에러 처리하는 부분을 리팩토링했습니다.
>
=> [Refactor] #262 회원가입기능 에러 처리 리팩토링

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt, app/src/main/res/layout/fragment_join.xml, app/src/main/res/layout/fragment_join_step3.xml
> #269 
> 성원님이 작업해주신 VBBaseFragment, DBBaseFragment 상속받아 프래그먼트 바인딩 null처리할 수 있도록 수정했습니다.
>
=> [#269] feature 프래그먼트 바인딩 널 처리

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt, app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
> #274
> DB 연결과 해제 코드 부분을 수정했습니다
> HikariCPDataSource를 사용하도록 수정했습니다
>
=> [Feat] #274 DB 연결 해제 코드 수정

app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt
> #291
> 스터디 글을 새로 작성 시 작성자 userIdx가 저장되도록 prefs 키값 변경
> "온라인" 칩을 골랐을 때 유효성 검사 생략
> 성원님이 prefs 수정하신 후 키값을 제가 변경 안해둬서 나타나는 버그라 키값 수정했습니다
=> [Bug #291] 글 작성시 글 작성자 정보가 안담기는 현상 수정

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep1Fragment.kt, app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep3Fragment.kt
> #295 
> SNS계정으로 회원가입 완료 후 파이어베이스 인증에 등록된 계정이 삭제되는 버그를 수정했습니다
> 이전 이슈에서 작성한 collectWhenStarted 함수가 일부 적용이 안된 부분이 있어 수정했습니다.
>
=> [#295] bug sns계정 회원가입 버그 수정

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
> #309 
>  sns 계정 회원가입 후 BottomNaviFragment에 joinType 전달하도록 수정했습니다.
>
=> [Feat] #309 sns 계정 회원가입 후 joinType 전달

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt, app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt, app/src/main/java/kr/co/lion/modigm/model/FavoriteData.kt, app/src/main/java/kr/co/lion/modigm/model/FilterStudyData.kt, app/src/main/java/kr/co/lion/modigm/model/StudyData.kt, app/src/main/java/kr/co/lion/modigm/model/StudyMemberData.kt, app/src/main/java/kr/co/lion/modigm/model/StudyTechStackData.kt, app/src/main/java/kr/co/lion/modigm/model/TechStackData.kt, app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudySearchViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFieldFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WritePeriodFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteProceedFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/WriteSkillFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/write/vm/WriteViewModel.kt, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/fragment_write_field.xml, app/src/main/res/layout/fragment_write_intro.xml, app/src/main/res/layout/fragment_write_period.xml, app/src/main/res/layout/fragment_write_proceed.xml, app/src/main/res/layout/fragment_write_skill.xml
#327 
1. 스터디, 필터 파트 쿼리 및 데이터 가공 구조 변경
2. 글작성 파트 코드 정리
코드 구조 변경이라 스크린 샷은 생략하겠습니다 !
전체데이터를 조회하고 해당 데이터를 데이터소스에서 가공하는 식으로 변경했습니다!
버그 확인 및 대대적으로 손보기가 목표였으나... 체력이슈로 쉽지 않네요..ㅋㅋ 일단 약간의 정리만 하고 올려봅니다! 
글쓰기 부분 선착순은 클릭되지 않고 추후 지원으로 변경하려고 손대려 했는데 뭔가 애매해서... 회의 때 이야기 해보고 지우던 다시 그리던 해보겠습니다! 이 부분 UI 약간 수정된 건  로직은 변함없으니... 잠시 무시하셔도 좋습니다 ㅋㅋㅋ
=> [#327] [Refactor] 필터 및 스터디 목록 리팩토링

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt, app/src/main/java/kr/co/lion/modigm/util/Extensions.kt
> #336 
> 스터디 상세페이지에 있는 신고하기 기능을 구글폼과 연결했습니다.
> 일단 설정에 있는 고객센터와 동일한 구글폼으로 연결했는데 신고를 위한 구글폼을 따로 만들어야 할까요?
=> [#336] feature 신고하기 기능 구글폼과 연결

app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileStudyFragment.kt
#355
ProfileStudyFragment에서 프래그먼트 전환 수정
당초 계획했던 기능 추가는 하지 않고 버그만 수정했습니다.
=> fix #355: ProfileStudyFragment에 있던 프래그먼트 전환을 replace로 변경

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
> #366 
> 회원가입 insertUserData 메서드 수정
>
=> [Fix] #366 회원가입 insertUserData 메서드 수정

app/src/main/res/layout/fragment_join_step2.xml
> #369 
> 회원가입 시 이름 입력 안내문구 추가
>
> 문구 수정이 필요하다면 말씀 부탁드립니다.
=> [Design] #369 회원가입 시 이름 입력 안내문구 추가

app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt, app/src/main/java/kr/co/lion/modigm/repository/ProfileRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/DeleteUserFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/vm/DeleteUserViewModel.kt, app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt, app/src/main/res/drawable/icon_person_remove_24.xml, app/src/main/res/layout/fragment_delete_user.xml, app/src/main/res/layout/fragment_settings.xml
> #370 
> 설정에 회원 탈퇴 기능을 추가했습니다
> 회원탈퇴를 진행하면 모든 DB 데이터가 삭제되고 로그인 화면으로 돌아갑니다.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/60c9a324-7b72-4c6e-bc13-4730316026d0" width="250px" /></td>
<td><img src="https://github.com/user-attachments/assets/b969df51-b78f-485b-8263-7334ec1a19f0" width="250px" /></td>
<td><img src="https://github.com/user-attachments/assets/9a5b8f01-df2f-4eb7-bef7-c61a4ab1aaab" width="250px" /></td>
</tr>
</table>
> 디자인 혹은 텍스트 수정이 필요한 부분이 있다면 말씀해주세요
=> [#370] feature 회원 탈퇴 기능 추가

app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDao.kt, app/src/main/java/kr/co/lion/modigm/db/login/RemoteLoginDataSource.kt, app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDao.kt, app/src/main/java/kr/co/lion/modigm/db/notification/RemoteNotificationDataSource.kt, app/src/main/java/kr/co/lion/modigm/repository/LoginRepository.kt, app/src/main/java/kr/co/lion/modigm/repository/NotificationRepository.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt, app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/login/LoginFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/login/vm/LoginViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt, app/src/main/java/kr/co/lion/modigm/ui/notification/vm/NotificationViewModel.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/popup/LogoutAdDialog.kt, app/src/main/java/kr/co/lion/modigm/util/Skill.kt, app/src/main/res/layout/fragment_detail_edit.xml
> #374
2차 테스트 버그 수정
1. 프로필 이미지 초기화 문제
2. 소개글 작성 edittext에 스크롤 추가
3. 알림페이지에 알림이 없는 경우 나오는 화면이 안보이는 문제
4. 참여중인 멤버 정렬 수정
5. 알림 배지 사라지는 문제
6. 스터디 정원이 다 찼을 경우 신청 막기
7. 신청하기 버튼 클릭시 스낵바 여러개 보이는 문제
8. 로그아웃 시 fcm토큰 삭제
9. 자동 로그인일 때만 fcm토큰이 저장되던 문제
10. 각 카테고리별 세부 항목에 있는 '기타'칩을 삭제, 카테고리의 '기타'칩만 사용하도록 수정
- 스크린 샷은 크게 달라진 부분은 없고 어색한 부분들만 개선된거라 딱히 추가 안해도 될것 같아서 넘어가겠습니다 
혹시 보고싶으신 부분이 있다면 comment남겨추세요 해당부분 촬영해서 수정해두겠습니다. 
- login과 setting쪽에 fcm토큰 관련 추가사항들 있습니다 확인 부탁드려요
=>  [feature #374] 2차 테스트 피드백 수정

app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/res/values/style.xml
#375 
1. 관심분야 칩에 폰트 적용
2. 프래그먼트가 add되어 백스택 문제가 있는 프래그먼트를 모두 replace로 수정
3. 글씨 크기가 고정되지 않은 텍스트를 모두 dp로 고정
스타일 파일에서 조정해서 글쓰기에서 보이는 칩 등도 같이 수정되었는데, 제가 확인해 봤을 때는 괜찮았으나 한 번 더 확인해주시면 감사하겠습니다.
=> #375 fix: 2차 테스트 피드백 적용

app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/res/values/style.xml
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
=> Revert "#375 fix: 2차 테스트 피드백 적용"

app/src/main/java/kr/co/lion/modigm/model/UserData.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/res/values/style.xml
#386 
깃 실수로 인한 재수정
1. 칩 폰트 적용
2. 프래그먼트 add로 인한 백스택 문제 해결
=> #386 fix: 2차 피드백 재수정

app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt, app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/layout/fragment_settings.xml
#394 
1. 버전 정보 텍스트뷰 크기 16dp로 고정
2. 관심분야가 없을 때 빈 칩이 나타나지 않도록 수정
| 칩 없을 때 프로필 수정 | 칩 없을 때 프로필 | 
|--|--|
=> #394 fix: 3차 테스트 피드백 수정
