APP-Android2/FinalProject-modigm

app/src/main/java/kr/co/lion/modigm/ui/login/OtherLoginFragment.kt
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_other_login.xml

> ex) #35
> 자체로그인 화면 구현입니다. 
트랜지션그룹도 설정했습니다.
역시 글꼴 미적용이에요!
버튼(텍스트버튼), 텍스트뷰, 체크박스 등 웬만하면 상위호환인 Material로 설정하려합니다.
추후 앱 구동 시에 테마문제가 있을지 모르겠는데, 문제가 생긴다면 빠르게 수정하겠습니다..ㅎㅎ

[Feature] #35 자체 로그인 화면 구현, Material 스타일로 전환

---

app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt

- (Group, 1:1) 채팅 방에 따라 맞게 보여지도록 하였습니다. 채팅 방으로 입장 하면 채팅 방 제목으로 잘 적용됩니다.
- 따로 고쳐야 할 부분 없으면 오늘(목요일)내로 Merge 해두겠습니다!

[#45] feat - ChatRoom 채팅방, 대화내용 (Group, 1:1) 분리

---

app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
app/src/main/res/layout/fragment_detail_edit.xml
app/src/main/res/values/style.xml

> ex) #67 
> 글 수정 화면 구현했습니다 
규모가 그리 안클거라 생각하고 바텀 시트까지 작업하다가 pr단위가 너무 커지는거 같아서 바텀시트 따로 pr날리겠습니다 
| 글 수정 화면 | 유효성 검사 |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/961970f2-836e-4556-b038-9a83afe3b83f" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/817daba7-12c5-4160-b42f-f132b95d2964" width=250 />| 
|장소선택(온라인) | 장소선택 (오프라인)|
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/7a691d13-695d-4ed9-9d49-d1bd3a290ee8" width=250 /> |<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/c5b4cd32-94b1-40e7-9edf-b72fa2614566" width=250 /> | 
> 툴바 title 과 툴바 구분선의 유무
> 유효성 검사를 한번에 할지 아님 스크린 샷처럼 하나씩 할지'
> 소개글 입력 칸의 …

[Feature #67] 글 상세 게시글 수정 화면 구현

---

app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatViewModel.kt
app/src/main/res/layout/fragment_chat.xml

> #77 
채팅 페이지 - 하단 바 추가등록 (클릭 된 하단 바 색상 변경 추가, Fragment 이동 추가)
채팅방 나가기 기능 추가 - Firebase에 ChatRoomData - chatMemberList에서 배열 안에 있는 현재 로그인한 아이디 제거
하단 바 Fragment이동, 채팅 방 나가기 정상 작동합니다 추가하거나 변경해야 할 부분이 있다면 말씀해주세요
이상이 없다면 30분 뒤(4시 35분 쯤)에 머지 하도록 하겠습니다!

[#77] feature - 채팅 하단 바 설정 및 채팅방 나가기 기능

---

app/src/main/java/kr/co/lion/modigm/db/remote/StudyDataSource.kt
app/src/main/java/kr/co/lion/modigm/model/StudyData.kt
app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/MainActivity.kt
app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudyFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyAllViewHolder.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudyMyViewHolder.kt
app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
app/src/main/res/layout/fragment_bottom_navi.xml
app/src/main/res/layout/fragment_filter_sort.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_study.xml
app/src/main/res/layout/fragment_study_all.xml
app/src/main/res/layout/fragment_study_my.xml

> #81 
> 스터디 목록관련 화면전환, 리사이클러뷰 데이터 연동 준비, 바텀내비게이션 구현 등 작업했습니다!
|전체 스터디|내 스터디|
|:---:|:---:|
|<img width="305" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/8925a3ae-3324-479b-af6b-ae140f362c49">|<img width="305" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/c6ba92b7-9403-4049-ad2a-c7a7bb6edc44">|
|스크롤 할 경우|
|:---:|
|<img width="304" alt="image" src="https://github.com/APP-Android2/FinalProject-modigm/assets/79239041/9c9dd0e5-1db1-4a77-a310-8c488305f50c">|
현재 데이터 연결이 안되어 있어서 목록은 나타나지 않네요!
데이터베이스 연동은 상황상 내일로 미뤘고(오히려 좋아) 미뤄뒀던 필터 화면과 로그인 API를 먼저 해봐야겠습니다. 
편하게 지적해주세요!

[#81] feature 스터디 목록 UI 데이터작업

---

app/google-services.json
app/src/main/java/kr/co/lion/modigm/model/ChatMessagesData.kt
app/src/main/java/kr/co/lion/modigm/model/ChatRoomData.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatGroupFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatOnetoOneFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/ChatRoomFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/ChatRoomAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/adapter/MessageAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/dao/ChatRoomDao.kt
app/src/main/java/kr/co/lion/modigm/ui/chat/vm/ChatViewModel.kt

> #85 
채팅 읽음/안읽음 메시지 관련 데이터 처리하여 채팅방 옆에 안읽은 개수가 바뀌도록 하였습니다
첫 번째 사진은 그냥 에뮬레이터 3개 띄워서 채팅 잘 되고있는 모습의 사진이며
두 번째 사진은 이번에 추가하게 된 읽지 않은 메시지의 개수를 띄워 줄 수 있는 사진입니다.
수정해야 할 부분이나 추가해야 할 부분이 있다면 말씀부탁드립니다.
없다면 5시 되기 전 쉬는시간에 머지 하겠습니다.

[#85] feature - 채팅 읽음안읽음 메시지 관련 데이터 처리

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/OnPlaceSelectedListener.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/PlaceSearchResultsAdapter.kt
app/src/main/res/drawable/icon_maps_location_24px.xml
app/src/main/res/layout/fragment_detail_edit.xml
app/src/main/res/layout/fragment_place_bottom_sheet.xml
app/src/main/res/layout/fragment_skill_bottom_sheet.xml
app/src/main/res/layout/row_place.xml

> ex) #104
> Google 장소 api 사용
> 게시글 수정화면에서 장소 입력 창을 누르면 바텀시트를 보여주고 원하는 장소를 검색해 리스트 항목을 누르면 해당 장소의 이름이 보이게 구현 했습니다.
> 사진은 아래 기술 스택 text 수정 전에 캡쳐한 사진입니다.
> 커밋 메시지에 이슈 번호 틀렸는데 죄송합니다...ㅎㅎ
> 아무생각없이 api key 입력한채로 push했다가 다시 수정했습니다 api키는 삭재 후 재생성 해서 바꿔놨어요 ㅠ
|장소 검색화면 | 장소검색 리스트 | 장소 선택 |
|--|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/76bf5ab3-f06f-4c3a-8604-a012f9894415" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/8f06b8b9-dbbd-4c7a-8730-6474de132aad" width=250 />| <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/3a6e5068-87fe-421b-857f-2fb9aec006e8" width=250 /> |
>
> 장소 검색 후 선택하면 장소 이름이 글 수정 화면에 보이는데 장소 입력 창 아래에 textview배치해서 상세주소를 가져오는게 …

[Feature #104] 게시글 수정 화면 장소 선택 bottomsheet 구현

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
app/src/main/res/layout/fragment_join_step1.xml
app/src/main/res/layout/fragment_join_step2.xml
app/src/main/res/layout/fragment_join_step3.xml

> #114 
> SNS계정으로 회원가입 시 전화번호 입력 화면부터 진행할 수 있도록 작업했습니다.
> 아직 SNS 로그인 기능이 미구현단계라서 실제 등록은 안되는 상태입니다.
> 추후 로그인과 회원가입 연결 시 SNS계정 로그인 후 커스텀 토큰과 로그인 타입을 번들에 담아서 JoinFragment에 전달해주시면 됩니다. (SNS 로그인 시 파이어베이스 인증과 연동하는 부분을 아직 몰라서 커스텀 토큰을 받는게 맞는지 다른 걸 받아야하는건지는 추후에 작업하면서 수정해보겠습니다)
>  키보드가 텍스트필드를 가리는 부분은 레이아웃에 스크롤뷰를 추가하는 방식으로 수정했습니다
>

[#114] feature 이메일 sns 계정에 따른 회원가입 절차 분기

---

app/src/main/java/kr/co/lion/modigm/ui/like/LikeFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/like/adapter/LikeAdapter.kt
app/src/main/res/layout/fragment_like.xml
app/src/main/res/layout/row_like.xml

> #113 
> 찜 화면 구현
> 하트 아이콘 클릭 이벤트는 DB연결하면서 구현 예정입니다
> 모집 상태가 모집 종료인 경우엔 회색으로 표시되도록 설정해뒀습니다.
> 활동 타입, 진행방식에 따라 text색상 설정 했습니다.
> 일단 깃에는 툴바 그림자 없이 올렸습니다. 첫번째 사진보시면 됩니다
|찜 화면(툴바 그림자 없음 / 18dp) | 찜 목록 없을 때 화면 (툴바 그림자 있음) |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/a7250340-9a90-4b72-bd42-b2b6861a2dcf" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/5cdb61b4-4f54-4d7f-b58e-0802274a267d" width=250 />|
|제목 글씨 크기 비교( 왼쪽 16dp / 오른쪽 18dp)|
|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/d547cd7a-5368-43f5-8013-d142580d1b15" /> | 
> 툴바 아래에 그림자 유무 만약 넣는게 괜찮다면 툴바랑 데이터 보이는 공간이랑 구분 안 가는 화면들(홈 제외)에도 넣는게 좋을 거 같습니다
> 제목 text 크기 엄청 큰 차이는 없긴한데 …

[Feature #113] 찜 화면 구현

---

app/src/main/java/kr/co/lion/modigm/ui/detail/CustomIntroDialog.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/res/layout/custom_dialog_intro_example.xml
app/src/main/res/layout/fragment_detail_edit.xml
app/src/main/res/layout/row_like.xml

> #127
> 태진님이 만드신 다이얼로그가 제 단말기 화면에서 크기가 이상해서 ㅠ 고칠까 하다가 일단 새로 만들었습니다.
> 글 상세 화면에서 삭제 메뉴를 눌렀을 때 다이얼로그가 표시되도록 했습니다.
> 화면 이동 코드 수정했습니다
> 좋아요 recyclerview 항목의 ui 간격 수정 했습니다. (짧아서 여기에 같이 올렸습니다)
|작성예시 다이얼로그 | 글 삭제 다이얼로그 |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/8d952762-2c61-4270-a8ee-28f732530bc1" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/c3b0d56d-0acc-4961-87b8-73a15943c9a1" width=250 />|
> 수정할 부분있으면 말씀해주세요!

[Feature #127] 글 수정 화면 다이얼로그 연결 및 글 상세화면 삭제 다이얼로그 구현

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
app/src/main/res/layout/fragment_join.xml
app/src/main/res/layout/fragment_join_step2.xml

> #138 
> SNS 계정으로 회원가입
> 회원가입 후SharedPreferences에 uid값 저장
>
> 테스트 번호가 아닌 실제 번호로 테스트할 시 에러가 발생하여 이 부분은 이슈 새로 발행 후 작업이 필요할 것 같습니다.
> 전화번호 중복 확인의 경우 파이어베이스 인증에 한번 로그인을 해줘야 중복확인이 가능한데 이렇게 되면
나중에 이메일(SNS) 계정과 전화번호를 연결할 때 전화 번호 인증 쪽에서 문제가 발생하는 것 같습니다.
전화번호로 계정 중복 여부를 파이어베이스에서 확인하지 않고 DB의 정보로 확인하는 걸로 절차를 바꿔야할 것 같은데
그렇게 된다면 user model에 어느 계정으로 가입했는지 확인하는 'provider' 추가가 필요할 것 같습니다.

[#138] feature sns 로그인 시 회원가입 진행

---

app/src/main/java/kr/co/lion/modigm/db/user/RemoteUserDataSource.kt
app/src/main/java/kr/co/lion/modigm/model/UserData.kt
app/src/main/java/kr/co/lion/modigm/repository/UserInfoRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
app/src/main/java/kr/co/lion/modigm/util/JoinType.kt
app/src/main/res/layout/fragment_join.xml

> #155 
> 전화번호 중복 확인 부분을 파이어베이스 인증에 등록된 계정 기준이 아닌 DB에 등록된 정보를 기준으로 확인하게 수정했습니다.
> 중복 계정에 대한 정보를 제공하기 위해 UserData에 userEmail, userProvider 필드 2개를 추가했습니다.
> DB에서 해당 전화번호로 유저 정보를 가져오는 메서드를 추가했습니다.
| 이메일 계정 | 카카오 계정 | 깃허브 계정 |
| -- | -- | -- |
| <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/c6f2952c-b33c-4f09-91c7-cf373ac31a22" width="350" /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/a0189fab-9e74-4143-932b-e4a7c0e6a02e" width="350" /> | <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/896faee7-f026-47a8-9314-b6814b03cfc6" width="350" /> |
| <img src="https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/17621d7d-e915-456f-888c-d738a4ed1a24" width="350" /> | <img …

[#155] feature 전화번호 중복 확인 기능 수정

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt

> #157 
> 전화번호 인증 부분을 수정했습니다.
> 이메일, SNS 계정과 전화번호 계정을 합쳐주는 과정을 수정했습니다.
전화번호 인증 후 관심분야 선택화면으로 넘어가기 전에 계정이 합쳐지며, JoinFragment 이탈 시 Firebase Auth에 등록된 계정이 삭제됩니다.
> 회원 가입 완료 후 StudyFragment가 아니라 BottomNaviFragment로 이동하도록 수정했습니다.
> 회원 가입 완료 후 SharedPreferences에 유저 정보 저장하도록 수정했습니다.
>

[#157] feature 회원가입 기능 디버깅

---

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailViewPagerAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
app/src/main/res/layout/row_detail_join_member.xml

>#170
> 스터디에 참여중인 멤버 데이터 연결
> 스터디장은 내보낼 수 없고 내보내기 text를 스터디장으로 변경
> 내보내기를 누르고 다이얼로그에서 확인을 누르면 참가자 목록에서 삭제
> 기본 이미지 및 error 이미지 설정
|데이터 연결 | 내보내기 다이얼로그 | 내보내기|
|--|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/c89b18b9-a965-4497-aa4b-fe3f3d28a09f" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/6f46890d-862e-4dc9-995b-e58f1358b923" width=250 />|<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/18c790b5-5646-4f38-b82c-5507cde596d5" width=250 />|
>

 [Feature #170] 멤버 목록 화면 구현

---

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt

> #173
> 글 상세 화면에서 게시글 삭제 클릭시 게시글 상태를 삭제로 변경
|글 삭제 버튼 | 글 삭제 다이얼로그 |
|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/f3672981-50df-4161-8af9-b2d59a02198e" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/21a14933-7a74-4243-a8a4-cf14a7bd2e49" width=250 />|
>
> 현재 삭제 후 백스택에서 해당 프래그먼트를 제거했더니 메인 스터디 화면에서 화면 갱신이 안됩니다

[Feature #173] 게시글 삭제처리

---

app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/StudyRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/NoMoveBehavior.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/like/LikeFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/like/adapter/LikeAdapter.kt
app/src/main/res/layout/fragment_detail.xml
app/src/main/res/layout/row_detail_apply_member.xml

> #196 
> 스터디 모집 방법이 선착순인 경우 참여하기 버튼을 누르면 바로 studyUidList에 추가 및 채팅방 이동
> 신청제인경우 신청하기 버튼을 누르면 신청이 완료되었습니다 snackBar가 보이고 studyApplyList에 추가
> 신청한사람이 있는 경우 대기중에 표시
> 승인을 누르면  studyUidList에 추가 및 참가중인 사람들에 추가
> 거절을 누르면 studyApplyList에서 삭제
> 멤버목록 화면 뒤로가기 추가
> 좋아요화면에서 글 상세로 이동(저번에 빼먹어서 여기서 추가했습니다)
> 글 상세화면에서 스낵바가 올라오면서 floating버튼이 위로 올라가는 걸 막았습니다
|대기중 화면 | 승인 | 참여중에 추가|
|--|--|--|
<image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/e602724d-d7e1-4842-af2b-1d6f712bd95b" width=250 /> | <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/7a5ec71d-3712-47b5-90db-436abb7e41f6" width=250 />| <image src="https://github.com/APP-Android2/FinalProject-modigm/assets/82036757/54dc3903-4ec0-4c05-aad3-d7bc5e4ef3c6" width=250 />|
> 리뷰어가 특별히 봐주었으면 하는 부분이 …

[Feature] 스터디 신청하기 구현

---

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt

#204
Detail 페이지에서 멤버 등록 및 내보내기 할 때 채팅 방 멤버에 등록 및 삭제 업데이트 되도록 하였습니다.
>

[#204] feature - 채팅 방 (멤버 등록 및 내보내기) 데이터 업데이트

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinStep2Fragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt
app/src/main/res/layout/fragment_join_step2.xml

> #206 
> 회원가입 시 이름을 한글만 입력가능하게 설정해놓았는데 이 부분에서 한글 입력이 안되는 버그가 발생하였습니다.
입력 제어 없이 모든 문자를 입력 가능하게 바꾸었습니다.
inputType은 뜬금없이 이메일로 되어있길래 text로 바꾸었습니다.
[Screen_recording_20240611_105235.webm](https://github.com/APP-Android2/FinalProject-modigm/assets/121005637/0f170f71-4225-4ae6-b9a4-d8ffd6a7f513)
>

[#206] Fix  이름 입력 수정

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt

> #212 
> 회원가입에서 로그인 화면으로 뒤로가기 로직 수정 및 파이어베이스 인증에 등록된 정보 삭제하는 로직 수정
>

[#212] Fix  뒤로가기 및 파이어베이스 인증 등록 정보 삭제 로직 수정

---

app/src/main/java/kr/co/lion/modigm/ui/write/WriteIntroFragment.kt
app/src/main/res/drawable/icon_photo_plus_24px.xml
app/src/main/res/layout/fragment_write_intro.xml

> #209
> 글작성 소개 탭에서 사진등록시 옆에 새로운 카드뷰가 생성되도록 수정(Detail Edit Fragment과 통일)

[#209] feature 등록한 사진이 옆으로 생기도록 수정

---

app/src/main/java/kr/co/lion/modigm/ui/profile/EditProfileFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/SettingsFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/vm/EditProfileViewModel.kt

#205 
1. 타인의 프로필을 볼 때 뒤로 가기 버튼을 누르면 설정 화면으로 이동하는 오류 해결
2. 프로필 수정 후 프로필 화면으로 돌아가면 화면이 업데이트되지 않는 문제 해결
-> profileFragment 객체를 전달해 업데이트 함수 호출

#205 fix: 프로필 수정 시 UI 업데이트

---

app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudySearchFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudySearchAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/study/adapter/StudySearchViewHolder.kt
app/src/main/java/kr/co/lion/modigm/util/FragmentName.kt
app/src/main/res/layout/fragment_study_search.xml

> #215 
스터디 검색기능 구현입니다.
서치뷰에 앞에 있는 아이콘은 이미 기능이 있어서 그런지 그걸 막고 새로운 클릭 리스너를 적용을 못하더군요. 
서치뷰를 구현을 다해놓고 툴바에 집어넣으려했더니 아이콘중첩을 없앨수가 없어서 그냥 이렇게 만들었습니다 ..ㅜ (서치바로 할껄) 
글자변경감지로 넣어서 바로바로 나오게, 다 지우면 다시 빈 리스트 반영하게 해놨습니다.

[#215] [Feature] 스터디 검색 기능 구현

---

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/JoinUserRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt

> #272 
> 전화번호 인증 계정 중복 확인 기능이 안되는 부분을 확인했고 중복 확인을 파이어스토어에서 체크하는 것에서 mysql에서 체크하는 것으로 수정했습니다.
> 테스트로 Hilt 어노테이션 붙여두었던 것을 미처 지우지 않아 실행 시 에러가 발생하여 삭제했습니다
>

[#272] bug 전화번호 인증 계정 중복 확인 기능 수정

---

app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt

> #281
> 회원가입 진행 시 전화번호 계정이 이메일(SNS)계정과 통합되지 않는 버그를 수정
>

[#281] bug  전화번호 계정 중복 확인 코드 수정

---

app/src/main/java/kr/co/lion/modigm/util/Extensions.kt

> #298
> flow collect해주는 확장 함수가 기존에 repeatOnLifecycle로 수행하는 코드였는데, 구글에서 권장하는 flowWithLifecycle로 변경했습니다.
collectWhenStarted 함수의 첫 번째 인자가 collect할 flow값이고, 두 번째 인자가 flow값 변경 시 수행할 람다입니다
변경 후 문제없이 실행되는 부분 확인했습니다
혹시라도 코드가 잘못되었거나 수정할 부분이 있다면 말씀 부탁드립니다.
>

[#298] collectWhenStarted 함수 수정

---

app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDao.kt
app/src/main/java/kr/co/lion/modigm/db/detail/SqlRemoteDetailDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/SqlDetailRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/PlaceBottomSheetFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/SkillBottomSheetFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt

> #303 
1. 상세화면 좋아요 작업
2. 상세화면에서 모집 상태 변경
변경 시 바로 데이터를 받아와서 UI를 갱신 시키면 일부 text들이 깜박 거리며 로딩되는 문제가 있어 DB 업데이트 성공 시, UI 갱신을 하지 않고 자체적으로 UI업데이트를 진행해 해결했습니다
3. 기존에는 채팅방으로 이동을 시켜야 해서 글 작성자도 본인의 스터디 상세글에서 신청하기버튼( 구 채팅방 이동하기 버튼)이 클릭이 되도록 했었지만 채팅기능을 제외하면 클릭기능이 필요 없을것 같아 막아뒀습니다.
>
> 기존 기능과 달라진 부분이나 추가된 부분이 크게 없어서 스크린 샷은 생략했습니다.
> 데이터베이스를 mysql로 변경하면서 달라진 부분들을 수정해서 재 구현 한거라 따로 스크린샷이나 영상은 안찍었지만 만약 보고싶으신 부분이 있으면 comment남겨주세요 수정해두겠습니다.

[feature #303] 상세화면 좋아요 적용

---

app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailApplyMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailJoinMemberFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailApplyMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/adapter/DetailJoinMembersAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/SqlDetailViewModel.kt
app/src/main/res/layout/fragment_detail_image_zoom.xml

> #303 
1. 스터디 커버 이미지를 눌러 상세 보기 기능을 추가 했습니다.
2. 파일명 변경 (파일명에서 Sql 삭제)

[feature #310] 스터디 상세화면 이미지 상세보기 기능

---

app/build.gradle.kts
app/src/main/java/kr/co/lion/modigm/db/study/RemoteStudyDao.kt
app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/FavoriteFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/FilterSortFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudyAllFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/StudyMyFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/vm/StudyViewModel.kt
app/src/main/res/layout/fragment_favorite.xml
app/src/main/res/layout/fragment_study_all.xml
app/src/main/res/layout/fragment_study_my.xml
app/src/main/res/layout/study_item_shimmer_layout.xml

#320 
1. 스터디 목록 스크롤 시 새로고침 구현
2. 스터디 목록이 뜨는 모든 리사이클러뷰 로딩 구현
3. 삭제한 스터디 찜목록, 내스터디 에서 안뜨도록 변경
4. 바텀내비 아이템 클릭으로 화면 전환 시 애니메이션 제거(hide/show -> replace)
5. 바텀내비 뒤로가기 로직 변경
|스크롤 새로고침+로딩|뒤로가기|
|:------------------------:|:---------:|
|<video src ="https://github.com/user-attachments/assets/028fc229-e946-4b5f-b7d8-b7ab9270de96" controls width="200">|<video src ="https://github.com/user-attachments/assets/b00d0ba5-a697-462a-a5f5-dd337d8b8a39" controls width="200">|
쓸어내려 새로고침 기능 넣어봤습니다. 적용되는 지 테스트 완료했습니다. 추후 써보시고 어색한 부분이 있다면 말씀 부탁드려요!
목록에 스터디 적용했습니다. 처음에 스켈레톤 UI를 적용해보려했는데, 데이터가 적어서 로딩이 짧아 이상해서 프로그래스바로 바꿨습니다. 이후 적용하게 될 것을 생각해서 만든 스켈레톤UI구성 코드는 약간 남긴 점 참고 부탁드립니다!(사실 아까워ㅅ...)
말씀해주신 삭제스터디 뜨는 문제 쿼리 변경으로 개선했습니다. 
가장 처음 add 후 다음 접근 시 show/hide 로 전환했었는데, 생명주기가 변하질 않아서 데이터 최신화가 애매하더군요. 빠르게 개선할만한 아이디어가 마땅히 …

[#320] [Feature] 스터디 목록 스크롤 시 새로고침 기능

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt

> #325 
> 자동로그인이 아닌 상태에서 로그아웃이 아닌 그냥 앱 종료 후에 회원가입에 진입했다가 취소할 경우 파이어베이스 인증 계정이 삭제되는 버그를 수정했습니다.
> 또한 계정중복안내프래그먼트를 보여주는 방식을 replace가 아니라 hide,show 방식으로 변경했습니다.
>

[#325]  파이어베이스 인증 계정이 삭제되는 버그 수정

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinStep2ViewModel.kt

> #335 
> sns 계정 회원가입 시 전화번호 통합이 안되는 버그가 있었는데 
> 회원가입 화면 진입 시 기존의 로그인 되었던 계정을 signout처리를 해주는 코드때문에 회원가입을 진행하면서 전화번호 인증 계정과 통합이 안되었던 것으로 확인했습니다.
> 이메일 계정 회원가입인 경우에만 미리 signout을 하는 로직으로 수정했습니다.
>

[#335] bug sns 계정 회원가입 시 전화번호 통합이 안되는 버그

---

app/src/main/java/kr/co/lion/modigm/db/join/RemoteJoinUserDao.kt
app/src/main/java/kr/co/lion/modigm/model/UserData.kt
app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt

> #356 
> userdata에 회원가입 일자(userJoinDate) 속성을 추가했습니다
> db에도 동일하게 userJoinDate로 필드를 추가했습니다
> 회원가입 시 현재 날짜가 저장됩니다.
> viewModelScope와 lifecycleScope가 별도의 scope인 관계로 fragment의 lifecycleScope에 에러 핸들러를 넣어도 viewModelScope의 에러를 잡지 못하는 것을 발견했습니다. 그래서 에러 핸들러를 viewModelScope에 전달하는 방식으로 코드를 수정했습니다.
>

[#356] feature userdata 회원가입 일자 속성 추가

---

app/build.gradle.kts
app/src/main/java/kr/co/lion/modigm/model/UserData.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
app/src/main/java/kr/co/lion/modigm/util/ModigmApplication.kt

> #362 
> UserData의 userJoinDate속성 타입을 Date에서 LocalDateTime으로 변경했습니다.
> 본 프로젝트의 min SDK 버전이 24인 관계로 26이상 부터 사용가능한 LocalDateTime을 26이하 버전에서도 사용할 수 있게 ThreeTen이라는 라이브러리를 추가했습니다.
> 제가 테스트 할때는 더 에러나는 부분이 없었는데 혹시 또 에러나는 부분이 있다면 제보 부탁드립니다.

[#362] feat userJoinDate 타입을 LocalDateTime으로 변경

---

app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDataSource.kt
app/src/main/java/kr/co/lion/modigm/repository/DetailRepository.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt

> #367 
1. 이미지 업로드 부분이 firebase storage로 되어있어 s3로 변경
2. 글 수정 화면에서 스터디 커버사진 변경 시 기존 s3에 저장된 커버사진 삭제 후 새 사진 업로드 
>

[fix #367] 이미지 업로드 s3로 변경, 스터디 커버 사진 변경시 기존 이미지 s3에서 삭제

---

app/src/main/java/kr/co/lion/modigm/ui/profile/DeleteUserFragment.kt
app/src/main/res/layout/fragment_delete_user.xml
app/src/main/res/layout/fragment_join_step2.xml
app/src/main/res/values/strings.xml

> #382 
> dp로 고정되어있지 않은 텍스트뷰의 텍스트 사이즈를 수정했습니다.
<table>
<tr>
<td width="250px"><img src="https://github.com/user-attachments/assets/62f1f982-9a62-4329-be52-99a3fa3f48bb" /></td>
<td width="250px"><img src="https://github.com/user-attachments/assets/66e27470-91b3-4b4e-bb3f-04d34f2a5c6e" /></td>
</tr>
</table>

[#382] feature 회원가입,탈퇴 텍스트뷰 사이즈 수정

---

app/src/main/java/kr/co/lion/modigm/db/profile/RemoteProfileDao.kt

> #391 
> 테이블의 제약조건 때문에 delete 구문이 실행되지 않아 회원탈퇴가 진행되지 않은 부분을 수정했습니다.
> 성원님이 각 테이블 제약조건에 ON DELETE CASCADE를 추가해주셔서 tb_user 테이블의 행만 삭제되면 관련된 테이블의 행도 같이 삭제됩니다.
> tb_favorite, tb_notification, tb_study, tb_study_member, tb_study_request, tb_study_tech_stack, tb_user, tb_user_fcm, tb_user_link 모든 테이블에 데이터를 추가한 후에 회원탈퇴를 시도하니 정상적으로 삭제가 되는 것을 확인했습니다.
>

[#391] fix 회원탈퇴가 안되는 버그 수정

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinDuplicateFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/join/vm/JoinViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/vm/DeleteUserViewModel.kt

> #385 
> 원래 코드로도 파이어베이스 인증 정보는 삭제가 되긴 하는데 어제와 같이 간혹 인증 정보가 삭제되지 않고 남아있는 경우가 있었습니다.
> 회원 탈퇴 시 인증 정보 삭제를 await한 후에 탈퇴 완료 처리하도록 수정했습니다.
> lifecyclescope나 viewmodelscope를 사용하는 경우에는 해당 코루틴 스코프가 생명주기에 맞추어 종료되기 때문에 fragment나 viewmodel이 빠르게 끝나는 경우에는 인증 정보 삭제 처리가 되지 않는 것 같아 코드를 수정했습니다.
>

[#385] Fix 파이어베이스 인증 정보 삭제가 안되는 버그 수정

---

app/src/main/java/kr/co/lion/modigm/db/detail/RemoteDetailDao.kt
app/src/main/java/kr/co/lion/modigm/model/NotificationData.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailEditFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/detail/vm/DetailViewModel.kt
app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/notification/NotificationService.kt
app/src/main/java/kr/co/lion/modigm/ui/notification/adapter/NotificationAdapter.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileWebFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/study/BottomNaviFragment.kt
app/src/main/res/layout/custom_menu_item.xml
app/src/main/res/layout/fragment_profile_web.xml
app/src/main/res/layout/row_notification.xml
app/src/main/res/menu/menu_profile_web.xml

> #388
1. 글 수정시 오픈 채팅 링크 사라짐, 링크 추가해도 저장 안되는 현상 수정
2. 알림 부분 글자 수 넘어갈 시 ... 생략 필요 maxLines, ellipsize설정 추가
3. 푸쉬 알림을 누르지 않고 앱을 실행 한 경우 바텀 네비 알림 탭에 배지가 안보이는 현상
4. detailfragment에서 링크를 클릭하거나 신고하기 버튼 클릭시 툴바가 잘려보이는 현상 수정
detailfragment를 통해서 웹뷰를 사용하는 경우 툴바가 반정도 잘려보이는 현상이 있었는데 fitsSystemWindows 속성을 사용해 수정했습니다.
5. 웹뷰의 툴바 완료 메뉴 글씨 크기 수정
툴바가 잘리는 현상 때문에 xml파일 수정하면서 해당 부분 수정해뒀습니다
6. 스터디 신청 취소, 탈퇴 기능 추가
|툴바 수정 및 메뉴 text크기 수정|
|--|
|<img src="https://github.com/user-attachments/assets/0377581a-f97f-41f9-9a6b-20b4cc60314a" width=300 /> |
|신청 취소, 스터디 탈퇴|
|:-----------------:|
|<video src="https://github.com/user-attachments/assets/a7908c6b-1f6c-4cd2-8d59-c310a12ad1bc" controls="controls" style="max-width: 100%; height: auto;"></video>|
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 …

[feature #388] 3차 테스트 피드백 수정

---

app/src/main/java/kr/co/lion/modigm/ui/detail/DetailFragment.kt
app/src/main/java/kr/co/lion/modigm/ui/profile/ProfileFragment.kt
app/src/main/java/kr/co/lion/modigm/util/Links.kt

> #396 
> 고객센터, 회원 신고, 스터디 신고에 연결되는 구글폼 추가 및 수정 작업
> 공지사항 수정
<table>
<tr><td>스터디 신고</td><td>회원 신고</td>
<tr>
<td width="350px"><video src="https://github.com/user-attachments/assets/08fbf814-e94f-482b-b5af-90eed78f58b9" /></td>
<td width="350px"><video src="https://github.com/user-attachments/assets/327b7ca0-e5f5-44f5-ab5d-6585511db636" /></td>
</tr>
<tr><td>고객센터</td><td>공지사항</td>
<tr>
<td><img src="https://github.com/user-attachments/assets/ba7faeb2-5b72-49f3-92d2-6cfc98cdfda7" /></td>
<td><img src="https://github.com/user-attachments/assets/75d22c96-76cf-4cd9-b02a-8d515aa155ea" /</td>
</tr>
</table>
> 구글폼에 숨김 문항이 없어서 idx값을 어쩔수 없이 노출시켜야하기 때문에 일부러 UUID로 랜덤값과 함께 붙여서서 신고글 번호로 보게 해놓았습니다. 
>구분 기호를 #으로 수정해놓았는데 영상이 수정 전 영상이라 언더바( _ )로 보여지는것만 참고해주시면 됩니다.

[#396] feat 고객센터, 회원 신고, 스터디 신고에 연결되는 구글폼 추가 및 수정 작업

---

app/src/main/java/kr/co/lion/modigm/ui/join/JoinFragment.kt

> #399 
> 전화번호 인증 후 다음화면에서 다시 이전 화면으로 돌아왔을때 바로 넘어갈 수 있도록 로직을 설정한 부분이 있었는데
처음 전화번호 인증 화면 진입 시 인증번호값이 공백인 것을 체크하는 것을 로직에 추가해놓지 않아서 바로 다음 화면으로 넘어가게 되었습니다.
로직 수정후 처음 전화번호 입력 화면 진입 시 제대로 유효성 체크가 되는 것을 확인했습니다.
>

[#399] fix 이름 전화번호 입력화면 넘어가지는 부분 수정
